---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-example-eks
  labels:
    app: eks-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-example
  template:
    metadata:
      labels:
        app: eks-example
    spec:
      containers:
      - name: aws-example-exp
        image: 841347124655.dkr.ecr.us-east-2.amazonaws.com/example-eks:2b48a6413e12dfebf8e6326a0b978003f9244270
        ports:
        - containerPort: 5000
