---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-example-exp
  labels:
    app: eks-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-example
  template:
    metadata:
      labels:
        app: eks-example
    spec:
      containers:
      - name: example-actions-flux-eks
        image: 841347124655.dkr.ecr.us-west-2.amazonaws.com/example-actions-flux-eks:bbc6a3fb93872a30f47a8a92f8589ac36ec1af6b
        ports:
        - containerPort: 5000
